using System.Collections.Generic;
using System.Linq;
using ProjectEulerProblems.Problem_2;
using Xunit;

namespace ProjectEulerProblems.Tests.Tests; 

/// <summary>
///     %%%%% Autogenerated class documentation from the IGT templates engine %%%%%
///     This class tests the operational functionality of the original source class
///     <see cref="Problem2Tests" />.
/// </summary>
public class Problem2Tests {
    [Fact]
    public void checkGeneratedsequence()
    {
        IEnumerable<int> expected = GenerateFake_fib();
        IEnumerable<int> actual = Lib.GenerateSequence(90);

        Assert.Equal(expected.Count(), actual.Count());
        Assert.Equal(expected.Sum(), actual.Sum());
    }

    public static IEnumerable<int> GenerateFake_fib()
    {
        return new List<int>
        {
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89
        };
    }

    [Fact]
    public void checkevensumwithgeneratedsequance()
    {
        IEnumerable<int> actual = Lib.GenerateSequence(90);

        Assert.Equal(44, Lib.SumOfEvenValues(actual));
    }
}